// Native pixel dimensions of the source files in static/, and a helper to
// build the srcset for the 640w/960w/1440w variants generated by
// scripts/generate-hero-srcset.js. Keeps PageHero.vue and the homepage
// parallax hero in sync without duplicating widths in every page.

export const heroImageDims: Record<string, { width: number; height: number }> = {
  '/action.jpg': { width: 1920, height: 2688 },
  '/headshot.jpg': { width: 1920, height: 1280 },
  '/perf2.jpg': { width: 1920, height: 2688 },
  '/perf4.jpg': { width: 1920, height: 1371 },
  '/perf5.jpg': { width: 1920, height: 1280 },
  '/reception-card-trick.jpg': { width: 1920, height: 1280 },
  '/reception-guest-laughing.jpg': { width: 1920, height: 1280 },
  '/skill.jpg': { width: 1920, height: 1280 },
  '/wedding-astonished-reaction.jpg': { width: 1920, height: 1280 },
  '/wedding-card-reveal.jpg': { width: 1920, height: 1280 },
  '/shuffle-cropped1.jpg': { width: 1920, height: 1279 },
}

const RESPONSIVE_WIDTHS = [640, 960, 1440]

export function heroSrcset(src: string): string {
  const dims = heroImageDims[src]
  const dot = src.lastIndexOf('.')
  const base = src.slice(0, dot)
  const ext = src.slice(dot)

  const entries = RESPONSIVE_WIDTHS.filter((w) => !dims || w < dims.width).map(
    (w) => `${base}-${w}w${ext} ${w}w`
  )
  entries.push(`${src} ${dims ? dims.width : 1920}w`)
  return entries.join(', ')
}
