// Native pixel dimensions of the sources in static/, and helpers to build the
// srcsets for the variants generated by scripts/generate-image-variants.js.
// Keep this list and that script's IMAGES in step.

export const imageDims: Record<string, { width: number; height: number }> = {
  '/action.jpg': { width: 1920, height: 2688 },
  '/headshot.jpg': { width: 1920, height: 1280 },
  '/perf2.jpg': { width: 1920, height: 2688 },
  '/perf3.jpg': { width: 1920, height: 2880 },
  '/perf4.jpg': { width: 1920, height: 1371 },
  '/perf5.jpg': { width: 1920, height: 1280 },
  '/promo-reaching.jpg': { width: 1230, height: 1483 },
  '/reception-card-trick.jpg': { width: 1920, height: 1280 },
  '/reception-guest-laughing.jpg': { width: 1920, height: 1280 },
  '/shuffle-cropped1.jpg': { width: 1920, height: 1279 },
  '/skill.jpg': { width: 1920, height: 1280 },
  '/vr.jpg': { width: 1920, height: 1280 },
  '/wedding-astonished-reaction.jpg': { width: 1920, height: 1280 },
  '/wedding-card-reveal.jpg': { width: 1920, height: 1280 },
  '/square/corporate.jpg': { width: 869, height: 868 },
  '/square/wedding-card-reveal.jpg': { width: 1280, height: 1280 },
}

export const logoDims: Record<string, { width: number; height: number }> = {
  '/Age-UK.jpg': { width: 1772, height: 900 },
  '/Arqiva.jpg': { width: 1612, height: 640 },
  '/BBC.jpg': { width: 600, height: 600 },
  '/Barclays.png': { width: 960, height: 960 },
  '/Btg.jpg': { width: 700, height: 400 },
  '/CAM.jpg': { width: 900, height: 900 },
  '/Disney.png': { width: 1280, height: 538 },
  '/GLive.jpg': { width: 969, height: 378 },
  '/Independent.png': { width: 1620, height: 1621 },
  '/Lloyds.png': { width: 645, height: 339 },
  '/Marriott.png': { width: 1280, height: 518 },
  '/Raddison.png': { width: 1024, height: 1024 },
  '/the-magic-circle.png': { width: 150, height: 150 },
}

const RESPONSIVE_WIDTHS = [400, 640, 960, 1440]
const LOGO_WIDTHS = [120, 240]

// Empty for anything absent from the dimension maps: only those files have
// generated variants, so guessing the names would point srcset at 404s.
function buildSrcset(
  src: string,
  tiers: number[],
  dimensions: Record<string, { width: number; height: number }>,
  extension?: string
): string {
  const dims = dimensions[src]
  if (!dims) return ''

  const dot = src.lastIndexOf('.')
  const base = src.slice(0, dot)
  const ext = extension || src.slice(dot)

  const entries = tiers
    .filter((w) => w < dims.width)
    .map((w) => `${base}-${w}w${ext} ${w}w`)
  entries.push(`${base}${ext} ${dims.width}w`)
  return entries.join(', ')
}

export function srcsetFor(src: string): string {
  return buildSrcset(src, RESPONSIVE_WIDTHS, imageDims)
}

export function webpSrcsetFor(src: string): string {
  return buildSrcset(src, RESPONSIVE_WIDTHS, imageDims, '.webp')
}

export function logoSrcsetFor(src: string): string {
  return buildSrcset(src, LOGO_WIDTHS, logoDims)
}

export function logoWebpSrcsetFor(src: string): string {
  return buildSrcset(src, LOGO_WIDTHS, logoDims, '.webp')
}
